E:\Download\Compressed\boost_1_65_1\bin.v2\tools\bcp\msvc-14.0\release\link-static\threading-multi\bcp ^
    boost/container/flat_map.hpp ^
    boost/container/flat_set.hpp ^
    boost/container/small_vector.hpp ^
    boost/container/static_vector.hpp ^
    boost/crc.hpp ^
    boost/icl/interval_map.hpp ^
    boost/optional.hpp ^
    boost/range.hpp ^
    boost/range/ ^
    boost/range/algorithm/ ^
    boost/range/algorithm_ext/ ^
    boost/smart_ptr/intrusive_ptr.hpp ^
    boost/variant/ ^
    --boost="%1" .
